version: "3.8"
services:
  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app_network

  app:
    container_name: ${APP_NAME}_app
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/public
    ports:
      - "8081:8081"
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /var/www/public
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    name: app

volumes:
  db_data:
    driver: local
